#Auto-generated by IDE. All changes by user will be lost
BASEDIR = $$_PRO_FILE_PWD_

INCLUDEPATH += $$BASEDIR/src
INCLUDEPATH += $$BASEDIR/src/controller
SOURCES += $$BASEDIR/src/*.cpp
SOURCES += $$BASEDIR/src/controller/*.cpp
HEADERS += $$BASEDIR/src/*.h*
HEADERS += $$BASEDIR/src/controller/*.h*

CONFIG += precompile_header
PRECOMPILED_HEADER = precompiled.h

lupdate_inclusion {
    SOURCES += $$BASEDIR/../assets/*.qml
}
 
TRANSLATIONS = \
    $${TARGET}.ts

